import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import 'font-awesome/css/font-awesome.css'
import 'bootstrap-social/bootstrap-social.css'
import Header from './Header';
import { Providers } from './provider';
import Footer from './Footer';

export const metadata = {
  title: 'Learning ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
        </Providers>
        <Footer />
      </body>
    </html>
  )
}
